#!/usr/bin/env perl

# $Id$

use strict;
use warnings;

my $formula = q{CH3(CH2)50CH3};
while (1) {
    print qq{formula: $formula\n};
    sleep 1;
    if ($formula =~ m/((?!H\d+([()]|$))([A-Z]([a-z])?\d*)+)/) {
        print qq{one\n};
        my $monomer = $1;
        my $weight = 0;
        while ($monomer =~ s/C//) {
            $weight += 12;
        }
        while ($monomer =~ s/H(\d*)//) {
            $weight += $1;
        }
        $formula =~ s/((?!H\d+([()]|$))([A-Z]([a-z])?\d*)+)/H$weight/;
        next;
    }
    if ($formula =~ m/\(H(\d+)\)(\d+)/) {
        print qq{two\n};
        my $weight = $1 * $2;
        $formula =~ s/\(H(\d+)\)(\d+)/H$weight/;
        next;
    }
    if ($formula =~ m/^(H(\d+))+$/) {
        print qq{three\n};
        my $weight = 0;
        while ($formula =~ s/H(\d+)//) {
            $weight += $1;
        }
        print qq{weight: $weight; formula: $formula\n};
        exit;
    }
}
