# Makefile.deps-ps is created from Makefile.deps-pdf
logparser.pdf.deps:								\
			build/logparser-flow-chart-part-1.pdf			\
			build/logparser-flow-chart-part-2.pdf			\
			build/graph-action-distribution.pdf			\
			build/graph-cached-regexes-vs-discarded-regexes.pdf	\
			build/graph-full-ruleset-vs-minimum-ruleset.pdf		\
			build/graph-hits.pdf					\
			build/graph-input-size-vs-parsing-time.pdf		\
			build/graph-input-size-vs-parsing-time-ratio.pdf	\
			build/graph-mails-received.pdf				\
			build/graph-normal-and-reverse-vs-shuffle.pdf
	touch "$@"

build/graph-cached-regexes-vs-discarded-regexes.pdf:	build/stats-cached-regexes-vs-discarded-regexes
build/graph-input-size-vs-parsing-time-ratio.pdf:	build/stats-input-size-vs-parsing-time
build/graph-input-size-vs-parsing-time.pdf:		build/results--skip_inserting_results--cache_compiled_regexes--normal_ordering--maximum_ruleset		\
							file-sizes.txt												\
							wc.txt
build/graph-hits.pdf:					build/stats-hits
build/graph-action-distribution.pdf:			build/stats-action-distribution
build/graph-full-ruleset-vs-minimum-ruleset.pdf:	build/stats-normal-full-ruleset-vs-minimum-ruleset	\
							build/stats-shuffle-full-ruleset-vs-minimum-ruleset	\
							build/stats-reverse-full-ruleset-vs-minimum-ruleset
build/graph-normal-and-reverse-relative-to-shuffle.pdf:	build/stats-normal-and-reverse-vs-shuffle
