# Makefile.deps-ps is created from Makefile.deps-pdf
logparser.deps: build/plot-cached-discarded-factor.ps			\
		build/plot-normal-filesize-numlines-factor.ps		\
		build/plot-normal-filesize-numlines.ps			\
		build/plot-hits.ps					\
		build/plot-action-distribution.ps			\
		build/plot-full-ruleset-vs-minimum-ruleset.ps		\
		build/plot-normal-and-reverse-relative-to-shuffle.ps	\
		build/plot-mails-received.ps

build/plot-cached-discarded-factor.ps: build/stats-cached-discarded-factor.txt
build/plot-normal-shuffle-reverse.ps: build/stats-normal.txt build/stats-shuffle.txt build/stats-reverse.txt
build/plot-normal-shuffle-factor.ps: build/stats-normal-shuffle-reverse-factor.txt 
build/plot-normal-reverse-factor.ps: build/stats-normal-shuffle-reverse-factor.txt
build/plot-normal-filesize-numlines-factor.ps: build/stats-normal-filesize-numlines-factor.txt
build/plot-normal-filesize-numlines.ps: build/stats-normal.txt file-sizes.txt wc.txt
build/plot-log22-distribution-by-rule.ps: stats-log22-distribution-by-rule.txt
build/plot-log22-distribution-versus-rule-count.ps: stats-log22-rule-count-by-program.txt
build/plot-hits.ps: stats-hits.txt
build/plot-hits-high.ps: stats-hits.txt
build/plot-hits-middle.ps: stats-hits.txt
build/plot-hits-low.ps: stats-hits.txt
build/plot-log22-log-lines.ps: stats-log22-rule-count-by-program.txt
build/plot-log22-rules.ps: stats-log22-rule-count-by-program.txt
build/plot-action-distribution.ps: build/action-distribution.txt
build/plot-full-ruleset-vs-minimum-ruleset.ps: build/stats-normal-full-ruleset-vs-minimum-ruleset.txt \
						build/stats-shuffle-full-ruleset-vs-minimum-ruleset.txt \
						build/stats-reverse-full-ruleset-vs-minimum-ruleset.txt
build/plot-normal-and-reverse-relative-to-shuffle.ps: build/stats-normal-shuffle-reverse-factor.txt
