# Makefile.deps-ps is created from Makefile.deps-pdf
logparser.deps: build/plot-cached-discarded-factor.pdf			\
		build/plot-normal-filesize-numlines-factor.pdf		\
		build/plot-normal-filesize-numlines.pdf			\
		build/plot-hits.pdf					\
		build/plot-action-distribution.pdf			\
		build/plot-full-ruleset-vs-minimum-ruleset.pdf		\
		build/plot-normal-and-reverse-relative-to-shuffle.pdf

build/plot-cached-discarded-factor.pdf: build/stats-cached-discarded-factor.txt
build/plot-normal-shuffle-reverse.pdf: build/stats-normal.txt build/stats-shuffle.txt build/stats-reverse.txt
build/plot-normal-shuffle-factor.pdf: build/stats-normal-shuffle-reverse-factor.txt 
build/plot-normal-reverse-factor.pdf: build/stats-normal-shuffle-reverse-factor.txt
build/plot-normal-filesize-numlines-factor.pdf: build/stats-normal-filesize-numlines-factor.txt
build/plot-normal-filesize-numlines.pdf: build/stats-normal.txt file-sizes.txt wc.txt
build/plot-log22-distribution-by-rule.pdf: stats-log22-distribution-by-rule.txt
build/plot-log22-distribution-versus-rule-count.pdf: stats-log22-rule-count-by-program.txt
build/plot-hits.pdf: stats-hits.txt
build/plot-hits-high.pdf: stats-hits.txt
build/plot-hits-middle.pdf: stats-hits.txt
build/plot-hits-low.pdf: stats-hits.txt
build/plot-log22-log-lines.pdf: stats-log22-rule-count-by-program.txt
build/plot-log22-rules.pdf: stats-log22-rule-count-by-program.txt
build/plot-action-distribution.pdf: build/action-distribution.txt
build/plot-full-ruleset-vs-minimum-ruleset.pdf: build/stats-normal-full-ruleset-vs-minimum-ruleset.txt \
						build/stats-shuffle-full-ruleset-vs-minimum-ruleset.txt \
						build/stats-reverse-full-ruleset-vs-minimum-ruleset.txt
build/plot-normal-and-reverse-relative-to-shuffle.pdf: build/stats-normal-shuffle-reverse-factor.txt
