#!/usr/bin/env perl

use strict;
use warnings;

use feature qw(say);

our %counts;
while (<>) {
    if (m/^(\w+) lines_by_action: (.*): (\d+)$/) {
        $counts{$2}{$1} = $3;
    }
}

my $sample_filename = (keys %counts)[0];
say q{# }, join q{ },
    sort keys %{$counts{$sample_filename}};
foreach my $filename (sort keys %counts) {
    say join q{ }, 
        map { $counts{$filename}{$_} }
            sort keys %{$counts{$filename}};
}
