#!/usr/bin/env perl

# $Id$

use strict;
use warnings;

use List::Util qw(sum);
use IO::File;

my $data_pipe = IO::File->new(q{bash mk-restriction-summary-data |})
    or die qq{$0: failed opening pipe from mk-restriction-summary-data: $!};

my %data;
while (<$data_pipe>) {
    chomp;
    my ($key, $value) = split /\|/, $_;
    $data{$key} = $value;
}

print q(\begin{tabular}[]{lrr}) . qq{\n};
print qq{Restriction type & Number of rejections & Percentage\\\\\n};

my $all_rejections = $data{q{All rejections}};
$data{q{Other restrictions}} = $all_rejections
    - (sum(values %data) - $all_rejections);
foreach my $key (sort { $data{$b} <=> $data{$a} || $a cmp $b } keys %data) {
    my $percentage = sprintf q{%.2f\%%}, ($data{$key} * 100 / $all_rejections);
    print qq{$key & $data{$key} & $percentage\\\\\n};
}

print q(\end{tabular}) . qq{\n};

