#!/usr/bin/env perl

# $Id$

use strict;
use warnings;

use File::Slurp;

print <<'HEADER';
\centering{}
\begin{tabular}[]{lrr}
    \tabletopline{}%
    & Mean & Std. Dev. \\
    \tablemiddleline{}%
HEADER

my ($label, $mean, $stddev);

foreach my $file (@ARGV) {
    my @lines = read_file($file);
    my %data;
    foreach my $line (@lines) {
        my ($key, $value) = split /: /, $line;
        $data{$key} = $value;
    }
    $label  = $data{q{Row}};
    chomp $label;
    $mean   = sprintf q{%.2f\%%}, $data{q{Mean}};
    $stddev = sprintf q{%.2f\%%}, $data{q{Standard deviation}};
    print qq{    $label & $mean & $stddev \\\\\n};
}

print <<'FOOTER';
    \tablebottomline{}%
\end{tabular}
FOOTER

