#!/usr/bin/env perl

# $Id$

use strict;
use warnings;

print <<'HEADER';
\centering{}
\begin{tabular}[]{lrr}
    \tabletopline{}%
    & Mean & Std. Dev. \\
    \tablemiddleline{}%
HEADER

my %data;
while (<>) {
    chomp;
    if (length) {
        my ($key, $value) = split /: /;
        $data{$key} = $value;
    } else {
        printf qq{    %s & %.2f\\%% & %.2f\\%% \\\\\n},
                        $data{q{Row}},
                        $data{q{Mean}},
                        $data{q{Standard deviation}};
    }
}

print <<'FOOTER';
    \tablebottomline{}%
\end{tabular}
FOOTER

