#!/usr/bin/env perl

# $Id$

use strict;
use warnings;

use File::Slurp;

my ($label, $mean, $stddev);

print q(\begin{tabular}[]{lrr}) . qq{\n};

$label  = q{};
$mean   = q{Mean};
$stddev = q{Std Dev};
print qq{$label & $mean & $stddev \\\\\n};

foreach my $file (@ARGV) {
    my @lines = read_file($file);
    my %data;
    foreach my $line (@lines) {
        my ($key, $value) = split /: /, $line;
        $data{$key} = $value;
    }
    $label  = $data{q{Row}};
    chomp $label;
    $mean   = sprintf q{%.2f\%%}, $data{q{Mean}};
    $stddev = sprintf q{%.2f\%%}, $data{q{Standard deviation}};
    print qq{$label & $mean & $stddev \\\\\n};
}

print q(\end{tabular}) . qq{\n};

