#!/bin/bash

# Run logparser a lot of times on all the input log files to generate 
# timing information to use in producing statistics.

set -u -e

if [ "$#" != 2 ]; then
    echo "Usage: $0 output-directory file-list" 1>&2
    exit 1
fi

dir="$1"
loglist="$2"
if [ ! -f "$loglist" ]; then
    echo "$0: $loglist is not a file" 1>&2
    exit 1;
fi
mkdir -p "$dir"

old_state=""
for log in $( < "$loglist" ); do
    filename=$( basename "$log" )
    state="$dir/state.$filename"
    in_state=
    if [ -f "$old_state" ]; then
        in_state="--in-statefile $old_state"
    fi
    date 1>&2
    echo "$filename: cat" 1>&2
    cat "$log" > /dev/null
    for i in $( seq 1 10 ); do
        echo "$filename: $i" 1>&2
        perl logparser --out-statefile "$state" $in_state --timing-data "$dir/timing.$filename.$i" "$log" 2> "$dir/warnings.$filename.$i"
    done
    old_state="$state"
    echo "$filename: finished" 1>&2
done
