#!/usr/bin/env perl

# $Id$

use strict;
use warnings;

use List::Util qw(sum);

my @values;
push @values, <>;
chomp @values;

my $num_values = @values;
my $mean = sum(@values) / $num_values;
my $sum_of_differences = 0;
foreach my $value (@values) {
    $sum_of_differences += (($value - $mean) ** 2);
}
my $stddev = sqrt ($sum_of_differences / $num_values);
foreach my $value (@values) {
    print qq{$value $mean\n};
}
