include ../common/Makefile

paper.pdf: ../../doc/logparser-acronyms.tex
paper.deps: build/plot-action-distribution.pdf \
			build/plot-normal-filesize-numlines.pdf \
			build/plot-normal-filesize-numlines-factor.pdf \
			build/plot-hits.pdf \
			build/plot-normal-shuffle-reverse-factor.pdf
paper.bbl: spmpsci.bst
